% RAMP 67
%%%%%%%%%%%%%%%%%%%%%%%%%%
% RampHW Netlist
%   Generated: 10/17/2020 11:33:53
%   PWD: C:\Users\Brandon\Desktop\glassbreak\model\dev\vAAD_ring-parts\v1_tie-together
%%%%%%%%%%%%%%%%%%%%%%%%%%


% Setup mid reference
ramp_ic.info.periph.ref.en_volt.val = 0;
ramp_ic.info.periph.ref.ext_volt.val = 1;


nethw = [];
nethw{end+1}=ramp_ic.pin.vcg({ ...
  'net',{'3','vcg'}, ...
});
nethw{end+1}=ramp_ic.pin.Iref({ ...
  'net',{'ref','vcg'}, ...
});
nethw{end+1}=ramp_ic.dev.pmir({ ...
  'loc',[2 0], ...
  'net',{'out','vcg'}, ...
  'bits',{'inSrcSign',1,'outSrcSign',1}, ...
  'nvm',{'outSrc','Vcg',1.7,'vcg3'}, ...
});
nethw{end+1}.nvmRef={3,2,0,'pmir_outSrc',1.7,3.5e-08,};
% nethw{end+1}=ramp_ic.dev.reg({ ...
%   'net',{'read','vdd'}, ...
%   'loc',[9 7], ...
%   'bits',{'bit',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.reg({ ...
%   'net',{'read','gnd'}, ...
%   'loc',[9 6], ...
%   'bits',{'bit',0}, ...
% });


nethw{end+1}=ramp_ic.pin.A0({ ...
  'net',{'in','inPos'}, ...
});
nethw{end+1}=ramp_ic.pin.A2({ ...
  'net',{'in','inNeg'}, ...
});
nethw{end+1}=ramp_ic.pin.A1({ ...
  'net',{'out','bpf_400'}, ...
});
nethw{end+1}=ramp_ic.pin.A3({ ...
															'net',{'out','rms_400'}, ...
														});
nethw{end+1}=ramp_ic.pin.D0({ ...
															'net',{'out','CmpTop'}, ...
});
%'net',{'out','preroll_trig'}, ...
% nethw{end+1}=ramp_ic.pin.D1({ ...
%   'net',{'out','thud_declare'}, ...
% });
% nethw{end+1}=ramp_ic.pin.D2({ ...
%   'net',{'out','blinky'}, ...
% });
% nethw{end+1}=ramp_ic.pin.D3({ ...
%   'net',{'out','shatter_declare'}, ...
% });
nethw{end+1}=ramp_ic.dev.vga({ ...
  'net',{'pos','inPos','neg','mid','ctrl','n/c','out','in_gain'}, ...
  'loc',[0 1], ...
  'nvm',{'num','gm',4.87836e-06,'vcg3','den','gm',0,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','mid','tap','n/c','mega','in_gain'}, ...
  'loc',[0 1], ...
});
nethw{end+1}=ramp_ic.dev.filt({ ...
  'net',{'inLPF','mid','inHPF','mid','inBPF','inPos','out2','bpf_4k'}, ...
  'loc',[1 6], ...
  'nvm',{'gm1','fc',4698.37,'vcg3','gm2','fc',4698.37,'vcg3','gm3','fc',4304.11,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','bpf_4k','out','rms_4k'}, ...
  'loc',[1 6 1], ...
  'nvm',{'atk','rate',500000,'vcg3','dec','rate',32.061,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.ota({ ...
  'net',{'pos','rms_4k','neg','mid','out','_rms_4k_log_intlogshift'}, ...
  'nvm',{'gm','gm',2.5198e-06,'vcg3','src','Id',4.8331e-09,'vcg3'}, ...
  'bits',{'log',1,'srcSign',0}, ...
  'loc',[2 5], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','rms_4k_log','well','rms_4k_log','gate','_rms_4k_log_intlogshift','drain','n/c'}, ...
  'loc',[3 5], ...
  'nvm',{'sourceCur','Id',2e-08,'vcg3','drainCur','Id',2e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[6 5], ...
  'nvm',{'gm1','gm',5.56228e-11,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
  'net',{'out','noise_4k_log','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','rms_4k_log','neg','noise_4k_log','nGate','n/c','pGate','n/c'}, ...
  'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.filt({ ...
  'net',{'inLPF','mid','inHPF','mid','inBPF','in_gain','out2','bpf_1k'}, ...
  'loc',[1 4], ...
  'nvm',{'gm1','fc',1306.39,'vcg3','gm2','fc',1306.39,'vcg3','gm3','fc',1115.14,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','bpf_1k','out','rms_1k'}, ...
  'loc',[1 4 1], ...
  'nvm',{'atk','rate',500000,'vcg3','dec','rate',10.0063,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.filt({ ...
  'net',{'inLPF','mid','inHPF','mid','inBPF','in_gain','out2','bpf_400'}, ...
  'loc',[1 3], ...
  'nvm',{'gm1','fc',520.043,'vcg3','gm2','fc',520.043,'vcg3','gm3','fc',409.225,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','bpf_400','out','rms_400'}, ...
  'loc',[1 3 1], ...
  'nvm',{'atk','rate',4494.41,'vcg3','dec','rate',1.3144,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.ota({ ...
  'net',{'pos','rms_400','neg','mid','out','_rms_400_log_intlogshift'}, ...
  'nvm',{'gm','gm',2.5332e-06,'vcg3','src','Id',4.6704e-09,'vcg3'}, ...
  'bits',{'log',1,'srcSign',0}, ...
  'loc',[2 2], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','rms_400_log','well','rms_400_log','gate','_rms_400_log_intlogshift','drain','n/c'}, ...
  'loc',[3 2], ...
  'nvm',{'sourceCur','Id',2e-08,'vcg3','drainCur','Id',2e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[6 2], ...
  'nvm',{'gm1','gm',7.722e-11,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
  'net',{'out','noise_400_log','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','rms_400_log','neg','noise_400_log','nGate','n/c','pGate','n/c'}, ...
  'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
});
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_4k','neg','mid','ctrl','n/c'}, ...
%   'loc',[3 6], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_4k_log','neg','noise_4k_log','ctrl','n/c'}, ...
%   'loc',[3 5], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_1k','neg','mid','ctrl','n/c'}, ...
%   'loc',[3 4], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_400','neg','mid','ctrl','n/c'}, ...
%   'loc',[3 3], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_400_log','neg','noise_400_log','ctrl','n/c'}, ...
%   'loc',[3 2], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 0], ...
%   'nvm',{'weight','Id',2.11005e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 1], ...
%   'nvm',{'weight','Id',3.4957e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 2], ...
%   'nvm',{'weight','Id',6.1875e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 3], ...
%   'nvm',{'weight','Id',3.31825e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 4], ...
%   'nvm',{'weight','Id',2.3455e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 5], ...
%   'nvm',{'weight','Id',4.1097e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 6], ...
%   'nvm',{'weight','Id',2.09725e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 7], ...
%   'nvm',{'weight','Id',3.8272e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 0], ...
%   'nvm',{'weight','Id',2.2751e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 1], ...
%   'nvm',{'weight','Id',3.9472e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 2], ...
%   'nvm',{'weight','Id',9.576e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 3], ...
%   'nvm',{'weight','Id',2.2358e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 4], ...
%   'nvm',{'weight','Id',5.088e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 5], ...
%   'nvm',{'weight','Id',3.84125e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 6], ...
%   'nvm',{'weight','Id',3.2661e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 7], ...
%   'nvm',{'weight','Id',2.7117e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 0], ...
%   'nvm',{'weight','Id',1.8429e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 1], ...
%   'nvm',{'weight','Id',6.9405e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 2], ...
%   'nvm',{'weight','Id',1.8618e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 3], ...
%   'nvm',{'weight','Id',4.59495e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 4], ...
%   'nvm',{'weight','Id',1.1274e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 5], ...
%   'nvm',{'weight','Id',7.601e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 6], ...
%   'nvm',{'weight','Id',3.63675e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 7], ...
%   'nvm',{'weight','Id',2.47965e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 0], ...
%   'nvm',{'weight','Id',3.84615e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 1], ...
%   'nvm',{'weight','Id',8.3795e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 2], ...
%   'nvm',{'weight','Id',2.1351e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 3], ...
%   'nvm',{'weight','Id',3.18285e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 4], ...
%   'nvm',{'weight','Id',1.42795e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 5], ...
%   'nvm',{'weight','Id',3.2035e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 6], ...
%   'nvm',{'weight','Id',3.44135e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 7], ...
%   'nvm',{'weight','Id',5.2705e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 0], ...
%   'nvm',{'weight','Id',8.215e-11,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 1], ...
%   'nvm',{'weight','Id',3.15325e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 2], ...
%   'nvm',{'weight','Id',3.7918e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 3], ...
%   'nvm',{'weight','Id',3.07205e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 4], ...
%   'nvm',{'weight','Id',5.338e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 5], ...
%   'nvm',{'weight','Id',1.1153e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 6], ...
%   'nvm',{'weight','Id',6.331e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 7], ...
%   'nvm',{'weight','Id',1.46995e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_0','outI','n/c'}, ...
%   'loc',[3 0], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.2475e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_1','outI','n/c'}, ...
%   'loc',[3 1], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',4.3474e-10,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_2','outI','n/c'}, ...
%   'loc',[3 2], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',6.163e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_3','outI','n/c'}, ...
%   'loc',[3 3], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',8.3671e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_4','outI','n/c'}, ...
%   'loc',[3 4], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',3.1732e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_5','outI','n/c'}, ...
%   'loc',[3 5], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.4092e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_6','outI','n/c'}, ...
%   'loc',[3 6], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',5.3428e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_7','outI','n/c'}, ...
%   'loc',[3 7], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',8.568e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_0','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 0], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_1','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 1], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_2','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 2], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_3','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 3], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_4','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 4], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_5','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 5], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_6','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 6], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_7','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 7], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 0 4], ...
%   'nvm',{'weight','Id',3.3374e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 0 5], ...
%   'nvm',{'weight','Id',5.1305e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 1 4], ...
%   'nvm',{'weight','Id',3.6952e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 1 5], ...
%   'nvm',{'weight','Id',9.481e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 2 4], ...
%   'nvm',{'weight','Id',6.1045e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 2 5], ...
%   'nvm',{'weight','Id',4.20185e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 3 4], ...
%   'nvm',{'weight','Id',2.0419e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 3 5], ...
%   'nvm',{'weight','Id',2.26865e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 4 4], ...
%   'nvm',{'weight','Id',6.7045e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 4 5], ...
%   'nvm',{'weight','Id',1.7257e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 5 4], ...
%   'nvm',{'weight','Id',0,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 5 5], ...
%   'nvm',{'weight','Id',3.7176e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 6 4], ...
%   'nvm',{'weight','Id',4.5702e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 6 5], ...
%   'nvm',{'weight','Id',9.1515e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 7 4], ...
%   'nvm',{'weight','Id',1.1177e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 7 5], ...
%   'nvm',{'weight','Id',2.33265e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_1_0','outI','n/c'}, ...
%   'loc',[4 4], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',3.2469e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_1_1','outI','n/c'}, ...
%   'loc',[4 5], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',7.7959e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_1_0','neg','mid','ctrl','n/c'}, ...
%   'loc',[5 4], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_1_1','neg','mid','ctrl','n/c'}, ...
%   'loc',[5 5], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 4 4], ...
%   'nvm',{'weight','Id',9.415e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 5 4], ...
%   'nvm',{'weight','Id',0,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 4 5], ...
%   'nvm',{'weight','Id',0,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 5 5], ...
%   'nvm',{'weight','Id',1.05235e-08,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_thud','outI','n/c'}, ...
%   'loc',[5 4], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',2.6262e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_shatter','outI','n/c'}, ...
%   'loc',[5 5], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.0319e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 4], ...
%   'nvm',{'gm1','gm',3.00912e-10,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
%   'net',{'out','thud_filt','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','nn_thud','neg','thud_filt','nGate','n/c','pGate','n/c'}, ...
%   'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 5], ...
%   'nvm',{'gm1','gm',1.31022e-10,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
%   'net',{'out','shatter_filt','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','nn_shatter','neg','shatter_filt','nGate','n/c','pGate','n/c'}, ...
%   'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.fgota({ ...
%   'net',{'pos','mid','neg','thud_filt','out','thud_cmp_cmp2int'}, ...
%   'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.48492,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
%   'loc',[4 4], ...
% });
% nethw{end+1}=ramp_ic.dev.mifg({ ...
% 																'net',{'source','vdd6','gate1','thud_cmp_cmp2int','gate2','thud_cmp_cmp2int','drain','thud_cmp'}, ...
% 																'loc',[5 4], ...
% 																'nvm',{'drainCur','Id',3e-07,'vcg3'}, ...
% 																'bits',{'pseudo',1}, ...
% 															});

% % nethw{end+1}=ramp_ic.dev.pfet({ ...
% %   'net',{'source','vdd2','well','vdd2','gate','thud_cmp_cmp2int','drain','thud_cmp'}, ...
% %   'loc',[3 4], ...
% %   'nvm',{'drainCur','Id',5e-07,'vcg3'}, ...
% % });
% % nethw{end+1}=ramp_ic.dev.reg({ ...
% % 															 'net',{'read','vdd2'}, ...
% % 															 'loc',[8 4], ...
% % 															 'bits',{'bit',1}, ...
% % 														 });
% nethw{end+1}=ramp_ic.dev.fgota({ ...
%   'net',{'pos','mid','neg','shatter_filt','out','shatter_cmp_cmp2int'}, ...
%   'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.53757,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
%   'loc',[4 6], ...
% });
% nethw{end+1}=ramp_ic.dev.mifg({ ...
% 																'net',{'source','vdd6','gate1','shatter_cmp_cmp2int','gate2','shatter_cmp_cmp2int','drain','shatter_cmp'}, ...
% 																'loc',[5 6], ...
% 																'nvm',{'drainCur','Id',3e-07,'vcg3'}, ...
% 																'bits',{'pseudo',1}, ...
% 															});
% % nethw{end+1}=ramp_ic.dev.pfet({ ...
% %   'net',{'source','vdd3','well','vdd3','gate','shatter_cmp_cmp2int','drain','shatter_cmp'}, ...
% %   'loc',[3 6], ...
% %   'nvm',{'drainCur','Id',5e-07,'vcg3'}, ...
% % });
% % nethw{end+1}=ramp_ic.dev.reg({ ...
% % 															 'net',{'read','vdd3'}, ...
% % 															 'loc',[8 6], ...
% % 															 'bits',{'bit',1}, ...
% % 														 });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 7], ...
%   'nvm',{'gm1','gm',0,'vcg3','gm2','gm',7e-07,'vcg3','pullCur','Id',2.62779e-09,'vcg3','pushCur','Id',2.30721e-11,'vcg3'}, ...
%   'net',{'out','thud_hang','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','thud_cmp','pGate','thud_cmp'}, ...
%   'bits',{'CTcap2TapSw',0,'CTcap1TapSw',1,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.mifg({ ...
%   'net',{'source','vdd6','gate1','thud_hang','gate2','thud_hang','drain','thud_hang_inv'}, ...
%   'loc',[5 7], ...
%   'nvm',{'drainCur','Id',3e-07,'vcg3'}, ...
%   'bits',{'pseudo',1}, ...
% });
% % nethw{end+1}=ramp_ic.dev.reg({ ...
% % 															 'net',{'read','vdd4'}, ...
% % 															 'loc',[8 7], ...
% % 															 'bits',{'bit',1}, ...
% % 														 });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 3], ...
%   'nvm',{'gm1','gm',0,'vcg3','gm2','gm',7e-07,'vcg3','pullCur','Id',6.34629e-10,'vcg3','pushCur','Id',2.03585e-11,'vcg3'}, ...
%   'net',{'out','shatter_hang','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','shatter_cmp','pGate','shatter_cmp'}, ...
%   'bits',{'CTcap2TapSw',0,'CTcap1TapSw',1,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.mifg({ ...
%   'net',{'source','vdd6','gate1','shatter_hang','gate2','shatter_hang','drain','shatter_hang_inv'}, ...
%   'loc',[5 3], ...
%   'nvm',{'drainCur','Id',3e-07,'vcg3'}, ...
%   'bits',{'pseudo',1}, ...
% });
% % nethw{end+1}=ramp_ic.dev.reg({ ...
% % 															 'net',{'read','vdd5'}, ...
% % 															 'loc',[8 3], ...
% % 															 'bits',{'bit',1}, ...
% % 														 });
% nethw{end+1}=ramp_ic.dev.clb({ ...
%   'net',{'a','thud_cmp','b','shatter_hang_inv','outD','thud_declare','outQ','n/c'}, ...
%   'loc',[9 3 0], ...
%   'lut',{'lutIn','A & B','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% });

% % 'net',{'a','shatter_cmp','b','thud_hang_inv','c','shatter_hang_inv','outD','shatter_declare','outQ','n/c'}, ...
% % 'lut',{'lutIn','A & ~B & C','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% nethw{end+1}=ramp_ic.dev.clb({ ...
% 															 'net',{'a','shatter_cmp','b','thud_hang_inv','c','shatter_hang_inv','outD','shatter_declare','outQ','n/c'}, ...
%   'loc',[9 6 0], ...
% 														 'lut',{'lutIn','A & ~B & C','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% });
% nethw{end+1}=ramp_ic.dev.clb({ ...
%   'net',{'a','shatter_declare','b','n/c','c','n/c','outD','blinky','outQ','n/c'}, ...
%   'loc',[9 5 0], ...
%   'lut',{'lutIn','~A','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% });
% nethw{end+1}=ramp_ic.dev.peak({ ...
%   'net',{'in','in_gain','out','in_gain_pktop'}, ...
%   'loc',[1 0 2], ...
%   'nvm',{'atk','rate',500000,'vcg3','dec','rate',426.616,'vcg3','buff','Id',1e-07,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.fgota({ ...
%   'net',{'pos','in_gain_pktop','neg','in_gain','out','CmpTop_cmp2int'}, ...
%   'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.49462,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
%   'loc',[4 0], ...
% });
% nethw{end+1}=ramp_ic.dev.pfet({ ...
%   'net',{'source','vdd6','well','vdd6','gate','CmpTop_cmp2int','drain','CmpTop'}, ...
%   'loc',[3 0], ...
%   'nvm',{'drainCur','Id',5e-07,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.reg({ ...
% 															 'net',{'read','vdd6'}, ...
% 															 'loc',[8 0], ...
% 															 'bits',{'bit',1}, ...
% 														 });
% nethw{end+1}=ramp_ic.dev.peak({ ...
%   'net',{'in','in_gain','out','in_gain_pkbot'}, ...
%   'loc',[1 1 2], ...
%   'nvm',{'atk','rate',442.625,'vcg3','dec','rate',500000,'vcg3','buff','Id',1e-07,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.fgota({ ...
%   'net',{'pos','in_gain','neg','in_gain_pkbot','out','CmpBot_cmp2int'}, ...
%   'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',2.2398,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
%   'loc',[4 1], ...
% });
% nethw{end+1}=ramp_ic.dev.pfet({ ...
%   'net',{'source','vdd6','well','vdd6','gate','CmpBot_cmp2int','drain','CmpBot'}, ...
%   'loc',[3 1], ...
%   'nvm',{'drainCur','Id',5e-07,'vcg3'}, ...
% });
% % nethw{end+1}=ramp_ic.dev.reg({ ...
% % 															 'net',{'read','vdd7'}, ...
% % 															 'loc',[8 1], ...
% % 															 'bits',{'bit',1}, ...
% % 														 });
% % 'net',{'a','CmpTop','b','n/c','c','CmpTop_rst','outD','n/c','outQ','CmpTop_trig'}, ...
% % 'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
% % nethw{end+1}=ramp_ic.dev.clb({ ...
% % 															 'net',{'a','CmpTop','b','n/c','c','CmpTop_rst','outD','n/c','outQ','CmpTop_trig'}, ...
% %   'loc',[9 0 0], ...
% % 														 'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
% % });
% % nethw{end+1}=ramp_ic.dev.clb({ ...
% % 															 'net',{'a','CmpTop_trig','b','n/c','c','n/c','outD','CmpTop_rst','outQ','n/c'}, ...
% % 															 'loc',[8 0 1], ...
% % 															 'lut',{'lutIn','A','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% % 														 });
% % nethw{end+1}=ramp_ic.dev.ms({ ...
% %   'loc',[6 0], ...
% %   'nvm',{'gm1','gm',0,'vcg3','gm2','gm',1e-06,'vcg3','pullCur','Id',9e-09,'vcg3','pushCur','Id',9e-09,'vcg3'}, ...
% %   'net',{'out','CmpTop_rst','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','CmpTop_trig','pGate','CmpTop_trig'}, ...
% %   'bits',{'CTcap2TapSw',0,'CTcap1TapSw',0,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
% % });
% % 'net',{'a','CmpBot','b','n/c','c','CmpBot_rst','outD','n/c','outQ','CmpBot_trig'}, ...
% % 'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
% % nethw{end+1}=ramp_ic.dev.clb({ ...
% % 															 'net',{'a','CmpBot','b','n/c','c','CmpBot_rst','outD','n/c','outQ','CmpBot_trig'}, ...
% %   'loc',[8 1 0], ...
% % 														 'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
% % });
% % nethw{end+1}=ramp_ic.dev.clb({ ...
% % 															 'net',{'a','CmpBot_trig','b','n/c','c','n/c','outD','CmpBot_rst','outQ','n/c'}, ...
% % 															 'loc',[8 1 1], ...
% % 															 'lut',{'lutIn','A','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% % 														 });
% % nethw{end+1}=ramp_ic.dev.ms({ ...
% %   'loc',[6 1], ...
% %   'nvm',{'gm1','gm',0,'vcg3','gm2','gm',1e-06,'vcg3','pullCur','Id',9e-09,'vcg3','pushCur','Id',9e-09,'vcg3'}, ...
% %   'net',{'out','CmpBot_rst','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','CmpBot_trig','pGate','CmpBot_trig'}, ...
% %   'bits',{'CTcap2TapSw',0,'CTcap1TapSw',0,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
% % });
% % nethw{end+1}=ramp_ic.dev.clb({ ...
% %   'net',{'a','CmpTop_trig','b','CmpBot_trig','c','n/c','outD','preroll_trig','outQ','n/c'}, ...
% %   'loc',[9 1 1], ...
% %   'lut',{'lutIn','A|B','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% % });
% nethw{end+1}=ramp_ic.dev.clb({ ...
%   'net',{'a','CmpTop','b','CmpBot','c','n/c','outD','preroll_trig','outQ','n/c'}, ...
%   'loc',[9 1 1], ...
%   'lut',{'lutIn','(~A)|(~B)','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% });
% % nethw{end+1}=ramp_ic.dev.fgota({ ...
% %   'net',{'pos','mid','neg','diff_amp_dc_ref','out','diff_amp_dc_ref'}, ...
% %   'nvm',{'gm','gm',2.5e-07,'vcg3','posCharge','Vcg',1.6,'vcg3','negCharge','Vcg',1.476,'vcg3'}, ...
% %   'loc',[4 2], ...
% % });
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','inPos','tap','n/c','mega','diff_amp_tap_pos'}, ...
  'loc',[0 2], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
																'net',{'kilo','diff_amp_tap_pos','tap','n/c','mega','diff_amp_amp_pos'}, ...
  'loc',[0 3], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_amp_pos','tap','n/c','mega','diff_amp_mid_buff'}, ...
  'loc',[0 4], ...
});
nethw{end+1}=ramp_ic.dev.opamp({ ...
																 'net',{'pos','mid','neg','diff_amp_mid_buff','out','diff_amp_mid_buff'}, ...
  'nvm',{'bias','Id',5e-08,'vcg3'}, ...
  'loc',[0 4], ...
});
% nethw{end+1}=ramp_ic.dev.resi({ ...
%   'net',{'kilo','inNeg','tap','n/c','mega','diff_amp_tap_neg'}, ...
%   'loc',[0 5], ...
% });
% nethw{end+1}=ramp_ic.dev.resi({ ...
% 																'net',{'kilo','diff_amp_tap_neg','tap','n/c','mega','diff_amp_amp_neg'}, ...
%   'loc',[0 6], ...
% });
% nethw{end+1}=ramp_ic.dev.resi({ ...
%   'net',{'kilo','diff_amp_amp_neg','tap','n/c','mega','diff_amp'}, ...
%   'loc',[0 7], ...
% });
% nethw{end+1}=ramp_ic.pin.A3({ ...
%   'net',{'out','diff_amp_amp_pos','fb','diff_amp_amp_neg','in','diff_amp'}, ...
% });
