%%%%%%%%%%%%%%%%%%%%%%%%%%
% RampHW Netlist - Just the mic interface to build a bitstream that Ring can use to get started
%   Hand-built from glass break trims
%   PWD: C:\Users\Brandon\Desktop\glassbreak\model\dev\vAAD_ring-parts\v1_tie-together
%%%%%%%%%%%%%%%%%%%%%%%%%%


% Setup mid reference
ramp_ic.info.periph.ref.en_volt.val = 0;
ramp_ic.info.periph.ref.ext_volt.val = 1;


nethw = [];
nethw{end+1}=ramp_ic.pin.vcg({ ...
  'net',{'3','vcg'}, ...
});
nethw{end+1}=ramp_ic.pin.Iref({ ...
  'net',{'ref','vcg'}, ...
});
nethw{end+1}=ramp_ic.dev.pmir({ ...
  'loc',[2 0], ...
  'net',{'out','vcg'}, ...
  'bits',{'inSrcSign',1,'outSrcSign',1}, ...
  'nvm',{'outSrc','Vcg',1.7,'vcg3'}, ...
});
nethw{end+1}.nvmRef={3,2,0,'pmir_outSrc',1.7,3.5e-08,};
nethw{end+1}=ramp_ic.dev.reg({ ...
															 'net',{'read','gndLoc'}, ...
															 'loc',[8 1], ...
															 'bits',{'bit',0}, ...
														 });
nethw{end+1}=ramp_ic.pin.A0({ ...
  'net',{'in','inPos'}, ...
});
nethw{end+1}=ramp_ic.pin.A2({ ...
  'net',{'in','inNeg'}, ...
});
nethw{end+1}=ramp_ic.pin.A1({ ...
															'net',{'out','vcg'}, ...
														});
nethw{end+1}=ramp_ic.pin.D0({ ...
															'net',{'out','gndLoc'}, ...
														});
nethw{end+1}=ramp_ic.pin.D1({ ...
															'net',{'out','gndLoc'}, ...
														});
nethw{end+1}=ramp_ic.pin.D2({ ...
															'net',{'out','gndLoc'}, ...
														});
nethw{end+1}=ramp_ic.pin.D3({ ...
															'net',{'out','gndLoc'}, ...
														});
nethw{end+1}=ramp_ic.dev.resi({ ...
	'net',{'kilo','inPos','tap','n/c','mega','diff_amp_amp_pos'}, ...
  'loc',[0 3], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_amp_pos','tap','n/c','mega','diff_amp_mid_buff'}, ...
  'loc',[0 4], ...
});
Vpos = 1.6; Vneg = Vpos - (1.024 - 0.6); %Vneg = Vpos;
nethw{end+1}=ramp_ic.dev.fgota({ ...
	'net',{'pos','mid','neg','diff_amp_dc_ref','out','diff_amp_dc_ref'}, ...
	'nvm',{'gm','gm',2.5e-07,'vcg3','posCharge','Vcg',Vpos,'vcg3','negCharge','Vcg',Vneg,'vcg3'}, ...
	'loc',[4 2], ...
});
nethw{end+1}=ramp_ic.dev.opamp({ ...
	'net',{'pos','diff_amp_dc_ref','neg','diff_amp_mid_buff','out','diff_amp_mid_buff'}, ...
  'nvm',{'bias','Id',5e-08,'vcg3'}, ...
  'loc',[0 4], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','inNeg','tap','n/c','mega','diff_amp_amp_neg'}, ...
  'loc',[0 6], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_amp_neg','tap','n/c','mega','diff_amp'}, ...
  'loc',[0 7], ...
});
nethw{end+1}=ramp_ic.pin.A3({ ...
  'net',{'out','diff_amp_amp_pos','fb','diff_amp_amp_neg','in','diff_amp'}, ...
});
