%%%%%%%%%%%%%%%%%%%%%%%%%%
% RampHW Netlist
%   Generated: 10/16/2020 12:20:10
%   PWD: C:\Users\Brandon\Desktop\glassbreak\model\dev\vAAD_ring-parts\v1_tie-together
%%%%%%%%%%%%%%%%%%%%%%%%%%


% Setup mid reference
ramp_ic.info.periph.ref.en_volt.val = 0;
ramp_ic.info.periph.ref.ext_volt.val = 1;


nethw = [];
nethw{end+1}=ramp_ic.pin.vcg({ ...
  'net',{'3','vcg'}, ...
});
nethw{end+1}=ramp_ic.pin.Iref({ ...
  'net',{'ref','vcg'}, ...
});
nethw{end+1}=ramp_ic.dev.pmir({ ...
  'loc',[2 0], ...
  'net',{'out','vcg'}, ...
  'bits',{'inSrcSign',1,'outSrcSign',1}, ...
  'nvm',{'outSrc','Vcg',1.7,'vcg3'}, ...
});
nethw{end+1}.nvmRef={3,2,0,'pmir_outSrc',1.7,3.5e-08,};
nethw{end+1}=ramp_ic.dev.reg({ ...
  'net',{'read','vdd'}, ...
  'loc',[9 7], ...
  'bits',{'bit',1}, ...
});
nethw{end+1}=ramp_ic.dev.reg({ ...
  'net',{'read','gnd'}, ...
  'loc',[9 6], ...
  'bits',{'bit',0}, ...
});
nethw{end+1}=ramp_ic.pin.A0({ ...
  'net',{'in','inPos'}, ...
});
nethw{end+1}=ramp_ic.pin.A2({ ...
  'net',{'in','inNeg'}, ...
});
% nethw{end+1}=ramp_ic.pin.A1({ ...
% 															'net',{'out','nn_thud'}, ...
% });
% nethw{end+1}=ramp_ic.pin.A3({ ...
% 															'net',{'out','nn_shatter'}, ...
% 														});
nethw{end+1}=ramp_ic.pin.D0({ ...
  'net',{'out','preroll_trig'}, ...
});



% nethw{end+1}=ramp_ic.pin.D1({ ...
%   'net',{'out','thud_cmp'}, ...
% });
% nethw{end+1}=ramp_ic.pin.D2({ ...
% 															'net',{'out','blinky'}, ...
% 														});
% nethw{end+1}=ramp_ic.pin.D3({ ...
%   'net',{'out','shatter_cmp'}, ...
% });




nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','mid','neg','diff_amp_dc_ref','out','diff_amp_dc_ref'}, ...
  'nvm',{'gm','gm',2.5e-07,'vcg3','posCharge','Vcg',1.6,'vcg3','negCharge','Vcg',1.476,'vcg3'}, ...
  'loc',[4 2], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','inPos','tap','n/c','mega','diff_amp_tap_pos'}, ...
  'loc',[0 1], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_tap_pos','tap','n/c','mega','diff_amp_amp_pos'}, ...
  'loc',[0 2], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_amp_pos','tap','n/c','mega','diff_amp_mid_buff'}, ...
  'loc',[0 3], ...
});
nethw{end+1}=ramp_ic.dev.opamp({ ...
  'net',{'pos','diff_amp_dc_ref','neg','diff_amp_mid_buff','out','diff_amp_mid_buff'}, ...
  'nvm',{'bias','Id',5e-08,'vcg3'}, ...
  'loc',[0 3], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
																'net',{'kilo','inNeg','tap','n/c','mega','diff_amp_tap_neg'}, ...
  'loc',[0 6], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
	'net',{'kilo','diff_amp_tap_neg','tap','n/c','mega','diff_amp_amp_neg'}, ...
  'loc',[0 5], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
																'net',{'kilo','diff_amp_amp_neg','tap','n/c','mega','diff_amp'}, ...
  'loc',[0 4], ...
});
nethw{end+1}=ramp_ic.pin.A3({ ...
  'net',{'out','diff_amp_amp_pos','fb','diff_amp_amp_neg','in','diff_amp'}, ...
});

% nethw{end+1}=ramp_ic.pin.A3({ ...
%   'net',{'out','inPos','fb','diff_amp','in','diff_amp'}, ...
% });




% nethw{end+1}=ramp_ic.dev.filt({ ...
%   'net',{'inLPF','mid','inHPF','mid','inBPF','inPos','out2','bpf_4k'}, ...
%   'loc',[1 6], ...
%   'nvm',{'gm1','fc',5905.61,'vcg3','gm2','fc',5905.61,'vcg3','gm3','fc',4845.82,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.peak({ ...
%   'net',{'in','bpf_4k','out','rms_4k'}, ...
%   'loc',[1 6 1], ...
%   'nvm',{'atk','rate',34095.1,'vcg3','dec','rate',117.619,'vcg3','buff','Id',5e-08,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.ota({ ...
%   'net',{'pos','rms_4k','neg','mid','out','_rms_4k_log_intlogshift'}, ...
%   'nvm',{'gm','gm',2.7885e-06,'vcg3','src','Id',3.305e-08,'vcg3'}, ...
%   'bits',{'log',1,'srcSign',1}, ...
%   'loc',[2 5], ...
% });
% nethw{end+1}=ramp_ic.dev.pfet({ ...
%   'net',{'source','rms_4k_log','well','rms_4k_log','gate','_rms_4k_log_intlogshift','drain','n/c'}, ...
%   'loc',[3 5], ...
%   'nvm',{'sourceCur','Id',2e-08,'vcg3','drainCur','Id',2e-07,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[6 5], ...
%   'nvm',{'gm1','gm',1.11538e-10,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
%   'net',{'out','noise_4k_log','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','rms_4k_log','neg','noise_4k_log','nGate','n/c','pGate','n/c'}, ...
%   'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
% });


% nethw{end+1}=ramp_ic.dev.filt({ ...
%   'net',{'inLPF','mid','inHPF','mid','inBPF','inPos','out2','bpf_1k'}, ...
%   'loc',[1 4], ...
%   'nvm',{'gm1','fc',1573.2,'vcg3','gm2','fc',1573.2,'vcg3','gm3','fc',1187.14,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.peak({ ...
%   'net',{'in','bpf_1k','out','rms_1k'}, ...
%   'loc',[1 4 1], ...
%   'nvm',{'atk','rate',7676.05,'vcg3','dec','rate',33.9343,'vcg3','buff','Id',5e-08,'vcg3'}, ...
% });


% nethw{end+1}=ramp_ic.dev.filt({ ...
%   'net',{'inLPF','mid','inHPF','mid','inBPF','inPos','out2','bpf_400'}, ...
%   'loc',[1 3], ...
%   'nvm',{'gm1','fc',705.047,'vcg3','gm2','fc',705.047,'vcg3','gm3','fc',473.631,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.peak({ ...
%   'net',{'in','bpf_400','out','rms_400'}, ...
%   'loc',[1 3 1], ...
%   'nvm',{'atk','rate',4638.96,'vcg3','dec','rate',10.432,'vcg3','buff','Id',5e-08,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.ota({ ...
%   'net',{'pos','rms_400','neg','mid','out','_rms_400_log_intlogshift'}, ...
%   'nvm',{'gm','gm',2.6725e-06,'vcg3','src','Id',2.7712e-08,'vcg3'}, ...
%   'bits',{'log',1,'srcSign',1}, ...
%   'loc',[2 2], ...
% });
% nethw{end+1}=ramp_ic.dev.pfet({ ...
%   'net',{'source','rms_400_log','well','rms_400_log','gate','_rms_400_log_intlogshift','drain','n/c'}, ...
%   'loc',[3 2], ...
%   'nvm',{'sourceCur','Id',2e-08,'vcg3','drainCur','Id',2e-07,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[6 2], ...
%   'nvm',{'gm1','gm',9.23266e-11,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
%   'net',{'out','noise_400_log','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','rms_400_log','neg','noise_400_log','nGate','n/c','pGate','n/c'}, ...
%   'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
% });
nethw{end+1}=ramp_ic.dev.reg({ ...
  'net',{'read','vddLoc'}, ...
  'loc',[8 0], ...
  'bits',{'bit',1}, ...
});
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_4k','neg','mid','ctrl','n/c'}, ...
%   'loc',[3 6], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_4k_log','neg','noise_4k_log','ctrl','n/c'}, ...
%   'loc',[3 5], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_1k','neg','mid','ctrl','n/c'}, ...
%   'loc',[3 4], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_400','neg','mid','ctrl','n/c'}, ...
%   'loc',[3 3], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','rms_400_log','neg','noise_400_log','ctrl','n/c'}, ...
%   'loc',[3 2], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 0], ...
%   'nvm',{'weight','Id',4.4735e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 1], ...
%   'nvm',{'weight','Id',4.6366e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 2], ...
%   'nvm',{'weight','Id',1.92815e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 3], ...
%   'nvm',{'weight','Id',5.9405e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 4], ...
%   'nvm',{'weight','Id',4.47895e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 5], ...
%   'nvm',{'weight','Id',2.50505e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 6], ...
%   'nvm',{'weight','Id',3.0433e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 6 7], ...
%   'nvm',{'weight','Id',5.811e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 0], ...
%   'nvm',{'weight','Id',2.73e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 1], ...
%   'nvm',{'weight','Id',2.88235e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 2], ...
%   'nvm',{'weight','Id',3.6282e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 3], ...
%   'nvm',{'weight','Id',5.3475e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 4], ...
%   'nvm',{'weight','Id',1.3867e-08,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 5], ...
%   'nvm',{'weight','Id',2.1646e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 6], ...
%   'nvm',{'weight','Id',3.7394e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 5 7], ...
%   'nvm',{'weight','Id',5.782e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 0], ...
%   'nvm',{'weight','Id',2.1339e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 1], ...
%   'nvm',{'weight','Id',2.2692e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 2], ...
%   'nvm',{'weight','Id',3.49975e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 3], ...
%   'nvm',{'weight','Id',4.2901e-10,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 4], ...
%   'nvm',{'weight','Id',1.95005e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 5], ...
%   'nvm',{'weight','Id',9.613e-10,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 6], ...
%   'nvm',{'weight','Id',3.89645e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 4 7], ...
%   'nvm',{'weight','Id',4.605e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 0], ...
%   'nvm',{'weight','Id',3.44145e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 1], ...
%   'nvm',{'weight','Id',2.94555e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 2], ...
%   'nvm',{'weight','Id',2.0217e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 3], ...
%   'nvm',{'weight','Id',1.08685e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 4], ...
%   'nvm',{'weight','Id',1.8456e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 5], ...
%   'nvm',{'weight','Id',3.148e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 6], ...
%   'nvm',{'weight','Id',2.68255e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 3 7], ...
%   'nvm',{'weight','Id',4.1553e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 0], ...
%   'nvm',{'weight','Id',7.284e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 1], ...
%   'nvm',{'weight','Id',3.135e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 2], ...
%   'nvm',{'weight','Id',2.2758e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 3], ...
%   'nvm',{'weight','Id',4.1396e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 4], ...
%   'nvm',{'weight','Id',2.0657e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 5], ...
%   'nvm',{'weight','Id',7.293e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 6], ...
%   'nvm',{'weight','Id',4.66885e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[3 2 7], ...
%   'nvm',{'weight','Id',1.38555e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_0','outI','n/c'}, ...
%   'loc',[3 0], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.7199e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_1','outI','n/c'}, ...
%   'loc',[3 1], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.202e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_2','outI','n/c'}, ...
%   'loc',[3 2], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.4412e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_3','outI','n/c'}, ...
%   'loc',[3 3], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.3763e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_4','outI','n/c'}, ...
%   'loc',[3 4], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',9.7935e-11,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_5','outI','n/c'}, ...
%   'loc',[3 5], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.9461e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_6','outI','n/c'}, ...
%   'loc',[3 6], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.4418e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_0_7','outI','n/c'}, ...
%   'loc',[3 7], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',5.0632e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_0','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 0], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_1','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 1], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_2','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 2], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_3','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 3], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_4','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 4], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_5','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 5], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_6','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 6], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_0_7','neg','mid','ctrl','n/c'}, ...
%   'loc',[4 7], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 0 4], ...
%   'nvm',{'weight','Id',2.0657e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 0 5], ...
%   'nvm',{'weight','Id',7.418e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 1 4], ...
%   'nvm',{'weight','Id',4.82965e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 1 5], ...
%   'nvm',{'weight','Id',1.38555e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 2 4], ...
%   'nvm',{'weight','Id',3.0997e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 2 5], ...
%   'nvm',{'weight','Id',4.7025e-10,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 3 4], ...
%   'nvm',{'weight','Id',4.40325e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 3 5], ...
%   'nvm',{'weight','Id',5.328e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 4 4], ...
%   'nvm',{'weight','Id',5.0325e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 4 5], ...
%   'nvm',{'weight','Id',6.389e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 5 4], ...
%   'nvm',{'weight','Id',7.2035e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 5 5], ...
%   'nvm',{'weight','Id',5.1145e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 6 4], ...
%   'nvm',{'weight','Id',5.9955e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 6 5], ...
%   'nvm',{'weight','Id',1.20285e-09,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 7 4], ...
%   'nvm',{'weight','Id',4.77535e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[4 7 5], ...
%   'nvm',{'weight','Id',1.8743e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_1_0','outI','n/c'}, ...
%   'loc',[4 4], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',2.9105e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_nn_thud_z_1_1','outI','n/c'}, ...
%   'loc',[4 5], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',2.964e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',0}, ...
% });


% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_1_0','neg','mid','ctrl','n/c'}, ...
%   'loc',[5 4], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnIn({ ...
%   'net',{'pos','nn_nn_thud_z_1_1','neg','mid','ctrl','n/c'}, ...
%   'loc',[5 5], ...
%   'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
%   'bits',{'IinSw',1,'sigSw',0,'reluSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 4 4], ...
%   'nvm',{'weight','Id',9.116e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 5 4], ...
%   'nvm',{'weight','Id',0,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 4 5], ...
%   'nvm',{'weight','Id',0,'vcg3'}, ...
%   'bits',{'sign',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnW({ ...
%   'loc',[5 5 5], ...
%   'nvm',{'weight','Id',5.262e-09,'vcg3'}, ...
%   'bits',{'sign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_thud','outI','n/c'}, ...
%   'loc',[5 4], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.3901e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });
% nethw{end+1}=ramp_ic.dev.nnOut({ ...
%   'net',{'outV','nn_shatter','outI','n/c'}, ...
%   'loc',[5 5], ...
%   'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',5.0526e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
%   'bits',{'IoutSw',0,'biasSign',1}, ...
% });



% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 4], ...
%   'nvm',{'gm1','gm',4.47376e-10,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
%   'net',{'out','thud_filt','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','nn_thud','neg','thud_filt','nGate','n/c','pGate','n/c'}, ...
%   'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
% });
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 5], ...
%   'nvm',{'gm1','gm',2.1999e-10,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
%   'net',{'out','shatter_filt','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','nn_shatter','neg','shatter_filt','nGate','n/c','pGate','n/c'}, ...
%   'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
% });



% nethw{end+1}=ramp_ic.dev.fgota({ ...
%   'net',{'pos','mid','neg','thud_filt','out','thud_cmp_cmp2int'}, ...
%   'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.33247-.045,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
%   'loc',[4 4], ...
% });
% nethw{end+1}=ramp_ic.dev.pfet({ ...
%   'net',{'source','vddLoc','well','vddLoc','gate','thud_cmp_cmp2int','drain','thud_cmp'}, ...
%   'loc',[3 4], ...
%   'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
% });
% nethw{end+1}=ramp_ic.dev.fgota({ ...
%   'net',{'pos','mid','neg','shatter_filt','out','shatter_cmp_cmp2int'}, ...
%   'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.41454-.05,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
%   'loc',[4 6], ...
% });
% nethw{end+1}=ramp_ic.dev.pfet({ ...
%   'net',{'source','vddLoc','well','vddLoc','gate','shatter_cmp_cmp2int','drain','shatter_cmp'}, ...
%   'loc',[3 6], ...
%   'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
% });


% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 7], ...
%   'nvm',{'gm1','gm',0,'vcg3','gm2','gm',7e-07,'vcg3','pullCur','Id',4.01293e-09,'vcg3','pushCur','Id',4.06139e-11,'vcg3'}, ...
%   'net',{'out','thud_hang','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','thud_cmp','pGate','thud_cmp'}, ...
%   'bits',{'CTcap2TapSw',0,'CTcap1TapSw',1,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
% });
% % added pfet to clean up the edge going to the clb
% nethw{end+1}=ramp_ic.dev.mifg({ ...
% 																'net',{'gate1','thud_hang','gate2','thud_hang','drain','thud_hang_inv'}, ...
% 																'loc',[5 7], ...
% 																'bits',{'pseudo', 1}, ...
% 																'nvm',{'sourceCur','Id',1e-6,'vcg3','drainCur','Id',0.3e-006,'vcg3'}, ...
% 															});
% nethw{end+1}=ramp_ic.dev.ms({ ...
%   'loc',[7 3], ...
%   'nvm',{'gm1','gm',0,'vcg3','gm2','gm',7e-07,'vcg3','pullCur','Id',6.9002e-10,'vcg3','pushCur','Id',4.21737e-11,'vcg3'}, ...
%   'net',{'out','shatter_hang','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','shatter_cmp','pGate','shatter_cmp'}, ...
%   'bits',{'CTcap2TapSw',0,'CTcap1TapSw',1,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
% });
% % added pfet to clean up the edge going to the clb
% nethw{end+1}=ramp_ic.dev.mifg({ ...
% 																'net',{'gate1','shatter_hang','gate2','shatter_hang','drain','shatter_hang_inv'}, ...
% 																'loc',[5 3], ...
% 																'bits',{'pseudo', 1}, ...
% 																'nvm',{'sourceCur','Id',1e-6,'vcg3','drainCur','Id',0.3e-006,'vcg3'}, ...
% 															});
% nethw{end+1}=ramp_ic.dev.clb({ ...
%   'net',{'a','thud_cmp','b','shatter_hang_inv','c','n/c','outD','thud_declare','outQ','n/c'}, ...
%   'loc',[9 3 0], ...
%   'lut',{'lutIn','A & B','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% });
% nethw{end+1}=ramp_ic.dev.clb({ ...
%   'net',{'a','shatter_cmp','b','thud_hang_inv','c','shatter_hang_inv','outD','shatter_declare','outQ','n/c'}, ...
%   'loc',[9 6 0], ...
%   'lut',{'lutIn','A & ~B & C','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% });

% nethw{end+1}=ramp_ic.dev.clb({ ...
% 															 'net',{'a','shatter_declare','outD','blinky','outQ','n/c'}, ...
% 															 'loc',[9 5 0], ...
% 															 'lut',{'lutIn','~A','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
% 														 });

% Preroll
nethw{end+1}=ramp_ic.dev.vga({ ...
  'net',{'pos','inPos','neg','mid','ctrl','n/c','out','preroll_in'}, ...
  'loc',[0 0], ...
  'nvm',{'num','gm',1.10997e-05,'vcg3','den','gm',0,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','mid','tap','n/c','mega','preroll_in'}, ...
  'loc',[0 0], ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','preroll_in','out','preroll_in_pktop'}, ...
  'loc',[1 0 2], ...
  'nvm',{'atk','rate',44137.9,'vcg3','dec','rate',656.885,'vcg3','buff','Id',1e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','preroll_in_pktop','neg','preroll_in','out','CmpTop_cmp2int'}, ...
  'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.49753,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
  'loc',[4 0], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','vddLoc','well','vddLoc','gate','CmpTop_cmp2int','drain','CmpTop'}, ...
  'loc',[3 0], ...
  'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','preroll_in','out','preroll_in_pkbot'}, ...
  'loc',[1 1 2], ...
  'nvm',{'atk','rate',650.145,'vcg3','dec','rate',500000,'vcg3','buff','Id',1e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','preroll_in','neg','preroll_in_pkbot','out','CmpBot_cmp2int'}, ...
  'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.49208,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
  'loc',[4 1], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','vddLoc','well','vddLoc','gate','CmpBot_cmp2int','drain','CmpBot'}, ...
  'loc',[3 1], ...
  'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','CmpTop','b','n/c','c','CmpTop_rst','outD','n/c','outQ','CmpTop_trig'}, ...
  'loc',[8 0 0], ...
  'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 0], ...
  'nvm',{'gm1','gm',0,'vcg3','gm2','gm',1e-06,'vcg3','pullCur','Id',9e-09,'vcg3','pushCur','Id',9e-09,'vcg3'}, ...
  'net',{'out','CmpTop_rst','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','CmpTop_trig','pGate','CmpTop_trig'}, ...
  'bits',{'CTcap2TapSw',0,'CTcap1TapSw',0,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','CmpBot','b','n/c','c','CmpBot_rst','outD','n/c','outQ','CmpBot_trig'}, ...
  'loc',[8 1 0], ...
  'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 1], ...
  'nvm',{'gm1','gm',0,'vcg3','gm2','gm',1e-06,'vcg3','pullCur','Id',9e-09,'vcg3','pushCur','Id',9e-09,'vcg3'}, ...
  'net',{'out','CmpBot_rst','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','CmpBot_trig','pGate','CmpBot_trig'}, ...
  'bits',{'CTcap2TapSw',0,'CTcap1TapSw',0,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','CmpTop_trig','b','CmpBot_trig','c','n/c','outD','preroll_trig','outQ','n/c'}, ...
  'loc',[8 1 1], ...
  'lut',{'lutIn','A|B','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
});
