%%%%%%%%%%%%%%%%%%%%%%%%%%
% RampHW Netlist
%   Generated: 10/08/2020 09:48:55
%   PWD: C:\Users\Brandon\Desktop\glassbreak\model\dev\vAAD_ring-parts\v0_basic-validation
%%%%%%%%%%%%%%%%%%%%%%%%%%


% Setup mid reference
ramp_ic.info.periph.ref.en_volt.val = 0;
ramp_ic.info.periph.ref.ext_volt.val = 1;


nethw = [];
nethw{end+1}=ramp_ic.pin.vcg({ ...
  'net',{'3','vcg'}, ...
});
nethw{end+1}=ramp_ic.pin.Iref({ ...
  'net',{'ref','vcg'}, ...
});
nethw{end+1}=ramp_ic.dev.pmir({ ...
  'loc',[2 0], ...
  'net',{'out','vcg'}, ...
  'bits',{'inSrcSign',1,'outSrcSign',1}, ...
  'nvm',{'outSrc','Vcg',1.7,'vcg3'}, ...
});
nethw{end+1}.nvmRef={3,2,0,'pmir_outSrc',1.7,3.5e-08,};
nethw{end+1}=ramp_ic.dev.reg({ ...
  'net',{'read','vdd'}, ...
  'loc',[9 7], ...
  'bits',{'bit',1}, ...
});
nethw{end+1}=ramp_ic.dev.reg({ ...
  'net',{'read','gnd'}, ...
  'loc',[9 6], ...
  'bits',{'bit',0}, ...
});
nethw{end+1}=ramp_ic.pin.A0({ ...
  'net',{'in','inPos'}, ...
});
nethw{end+1}=ramp_ic.pin.A2({ ...
  'net',{'in','inNeg'}, ...
});
nethw{end+1}=ramp_ic.pin.A1({ ...
  'net',{'out','thud_declare'}, ...
});

% nethw{end+1}=ramp_ic.pin.A1({ ...
%   'net',{'out','thud_filt'}, ...
% });
% nethw{end+1}=ramp_ic.pin.D0({ ...
%   'net',{'out','preroll_trig'}, ...
% });
% nethw{end+1}=ramp_ic.pin.D1({ ...
%   'net',{'out','thud_declare'}, ...
% });
% nethw{end+1}=ramp_ic.pin.D3({ ...
%   'net',{'out','shatter_declare'}, ...
% });
nethw{end+1}=ramp_ic.dev.filt({ ...
  'net',{'inLPF','mid','inHPF','mid','inBPF','inPos','out2','bpf_0'}, ...
  'loc',[1 3], ...
  'nvm',{'gm1','fc',547.822,'vcg3','gm2','fc',547.822,'vcg3','gm3','fc',966.125,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','bpf_0','out','rms_0'}, ...
  'loc',[1 3 1], ...
  'nvm',{'atk','rate',4638.65,'vcg3','dec','rate',10.3015,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','rms_0','out','rms_0_min'}, ...
  'loc',[1 4 1], ...
  'nvm',{'atk','rate',21.5749,'vcg3','dec','rate',1415.94,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.filt({ ...
  'net',{'inLPF','mid','inHPF','mid','inBPF','inPos','out2','bpf_1'}, ...
  'loc',[1 5], ...
  'nvm',{'gm1','fc',5808.72,'vcg3','gm2','fc',5808.72,'vcg3','gm3','fc',6679.3,'vcg3','buff2','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','bpf_1','out','rms_1'}, ...
  'loc',[1 5 1], ...
  'nvm',{'atk','rate',35326.5,'vcg3','dec','rate',102.771,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','rms_1','out','rms_1_min'}, ...
  'loc',[1 6 1], ...
  'nvm',{'atk','rate',27.0366,'vcg3','dec','rate',833.727,'vcg3','buff','Id',5e-08,'vcg3'}, ...
});

nethw{end+1}=ramp_ic.dev.reg({ ...
  'net',{'read','vddLoc'}, ...
  'loc',[8 0], ...
  'bits',{'bit',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','rms_0','neg','mid','ctrl','n/c'}, ...
  'loc',[3 3], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','rms_0_min','neg','mid','ctrl','n/c'}, ...
  'loc',[3 4], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','rms_1','neg','mid','ctrl','n/c'}, ...
  'loc',[3 5], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','rms_1_min','neg','mid','ctrl','n/c'}, ...
  'loc',[3 6], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 0], ...
  'nvm',{'weight','Id',6.438e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 1], ...
  'nvm',{'weight','Id',3.22685e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 2], ...
  'nvm',{'weight','Id',1.6999e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 3], ...
  'nvm',{'weight','Id',1.3623e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 4], ...
  'nvm',{'weight','Id',7.599e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 5], ...
  'nvm',{'weight','Id',3.1295e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 6], ...
  'nvm',{'weight','Id',1.2946e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 3 7], ...
  'nvm',{'weight','Id',2.1743e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 0], ...
  'nvm',{'weight','Id',1.19675e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 1], ...
  'nvm',{'weight','Id',1.1143e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 2], ...
  'nvm',{'weight','Id',2.20495e-10,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 3], ...
  'nvm',{'weight','Id',3.28665e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 4], ...
  'nvm',{'weight','Id',5.427e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 5], ...
  'nvm',{'weight','Id',5.1255e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 6], ...
  'nvm',{'weight','Id',4.17445e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 4 7], ...
  'nvm',{'weight','Id',4.94145e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 0], ...
  'nvm',{'weight','Id',1.2572e-08,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 1], ...
  'nvm',{'weight','Id',3.45995e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 2], ...
  'nvm',{'weight','Id',4.51645e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 3], ...
  'nvm',{'weight','Id',2.13875e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 4], ...
  'nvm',{'weight','Id',5.709e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 5], ...
  'nvm',{'weight','Id',5.782e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 6], ...
  'nvm',{'weight','Id',2.40555e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 5 7], ...
  'nvm',{'weight','Id',1.8969e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 0], ...
  'nvm',{'weight','Id',2.2556e-10,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 1], ...
  'nvm',{'weight','Id',4.80385e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 2], ...
  'nvm',{'weight','Id',2.4972e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 3], ...
  'nvm',{'weight','Id',4.82835e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 4], ...
  'nvm',{'weight','Id',1.019e-08,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 5], ...
  'nvm',{'weight','Id',4.80385e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 6], ...
  'nvm',{'weight','Id',3.403e-10,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[3 6 7], ...
  'nvm',{'weight','Id',4.46605e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_0','outI','n/c'}, ...
  'loc',[3 0], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',3.8648e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_1','outI','n/c'}, ...
  'loc',[3 1], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',5.6989e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_2','outI','n/c'}, ...
  'loc',[3 2], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.2035e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_3','outI','n/c'}, ...
  'loc',[3 3], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.9153e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_4','outI','n/c'}, ...
  'loc',[3 4], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',2.0916e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_5','outI','n/c'}, ...
  'loc',[3 5], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',9.1079e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_6','outI','n/c'}, ...
  'loc',[3 6], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',6.3621e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_0_7','outI','n/c'}, ...
  'loc',[3 7], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.7545e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_0','neg','mid','ctrl','n/c'}, ...
  'loc',[4 0], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_1','neg','mid','ctrl','n/c'}, ...
  'loc',[4 1], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_2','neg','mid','ctrl','n/c'}, ...
  'loc',[4 2], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_3','neg','mid','ctrl','n/c'}, ...
  'loc',[4 3], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_4','neg','mid','ctrl','n/c'}, ...
  'loc',[4 4], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_5','neg','mid','ctrl','n/c'}, ...
  'loc',[4 5], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_6','neg','mid','ctrl','n/c'}, ...
  'loc',[4 6], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_0_7','neg','mid','ctrl','n/c'}, ...
  'loc',[4 7], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 0 4], ...
  'nvm',{'weight','Id',6.851e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 0 5], ...
  'nvm',{'weight','Id',3.7312e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 1 4], ...
  'nvm',{'weight','Id',4.1344e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 1 5], ...
  'nvm',{'weight','Id',4.28125e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 2 4], ...
  'nvm',{'weight','Id',3.03925e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 2 5], ...
  'nvm',{'weight','Id',1.23675e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 3 4], ...
  'nvm',{'weight','Id',4.4543e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 3 5], ...
  'nvm',{'weight','Id',3.813e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 4 4], ...
  'nvm',{'weight','Id',8.1375e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 4 5], ...
  'nvm',{'weight','Id',5.663e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 5 4], ...
  'nvm',{'weight','Id',1.13995e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 5 5], ...
  'nvm',{'weight','Id',2.76805e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 6 4], ...
  'nvm',{'weight','Id',2.7725e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 6 5], ...
  'nvm',{'weight','Id',1.26335e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 7 4], ...
  'nvm',{'weight','Id',4.6347e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[4 7 5], ...
  'nvm',{'weight','Id',5.0135e-09,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_1_0','outI','n/c'}, ...
  'loc',[4 4], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',2.7211e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_nn_thud_z_1_1','outI','n/c'}, ...
  'loc',[4 5], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',2.719e-09,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_1_0','neg','mid','ctrl','n/c'}, ...
  'loc',[5 4], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnIn({ ...
  'net',{'pos','nn_nn_thud_z_1_1','neg','mid','ctrl','n/c'}, ...
  'loc',[5 5], ...
  'nvm',{'gmV2I','gm',1e-07,'vcg3','u','Id',5e-09,'vcg3'}, ...
  'bits',{'IinSw',1,'sigSw',0,'reluSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[5 4 4], ...
  'nvm',{'weight','Id',4.6296e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[5 5 4], ...
  'nvm',{'weight','Id',0,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[5 4 5], ...
  'nvm',{'weight','Id',0,'vcg3'}, ...
  'bits',{'sign',0}, ...
});
nethw{end+1}=ramp_ic.dev.nnW({ ...
  'loc',[5 5 5], ...
  'nvm',{'weight','Id',5.4525e-09,'vcg3'}, ...
  'bits',{'sign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_thud','outI','n/c'}, ...
  'loc',[5 4], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',9.4235e-11,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.nnOut({ ...
  'net',{'outV','nn_shatter','outI','n/c'}, ...
  'loc',[5 5], ...
  'nvm',{'gmI2V','gm',1e-07,'vcg3','bias','Id',1.7534e-08,'vcg3','buff','Id',5e-08,'vcg3'}, ...
  'bits',{'IoutSw',0,'biasSign',1}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 4], ...
  'nvm',{'gm1','gm',7.59147e-10,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
  'net',{'out','thud_filt','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','nn_thud','neg','thud_filt','nGate','n/c','pGate','n/c'}, ...
  'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 5], ...
  'nvm',{'gm1','gm',1.01516e-09,'vcg3','gm2','gm',5e-08,'vcg3','pullCur','Id',0,'vcg3','pushCur','Id',0,'vcg3'}, ...
  'net',{'out','shatter_filt','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','nn_shatter','neg','shatter_filt','nGate','n/c','pGate','n/c'}, ...
  'bits',{'CTcap2TapSw',1,'CTcap1TapSw',1,'CTcapRatio',1,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',1,'ota2vgnd',0,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','mid','neg','thud_filt','out','thud_cmp_cmp2int'}, ...
  'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.48005,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
  'loc',[4 3], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','vddLoc','well','vddLoc','gate','thud_cmp_cmp2int','drain','thud_cmp'}, ...
  'loc',[3 3], ...
  'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','mid','neg','shatter_filt','out','shatter_cmp_cmp2int'}, ...
  'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.4224,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
  'loc',[4 6], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','vddLoc','well','vddLoc','gate','shatter_cmp_cmp2int','drain','shatter_cmp'}, ...
  'loc',[3 6], ...
  'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 7], ...
  'nvm',{'gm1','gm',0,'vcg3','gm2','gm',7e-07,'vcg3','pullCur','Id',3.33306e-09,'vcg3','pushCur','Id',5.63514e-11,'vcg3'}, ...
  'net',{'out','thud_hang','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','thud_cmp','pGate','thud_cmp'}, ...
  'bits',{'CTcap2TapSw',0,'CTcap1TapSw',1,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 3], ...
  'nvm',{'gm1','gm',0,'vcg3','gm2','gm',7e-07,'vcg3','pullCur','Id',9.74484e-10,'vcg3','pushCur','Id',5.95542e-11,'vcg3'}, ...
  'net',{'out','shatter_hang','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','shatter_cmp','pGate','shatter_cmp'}, ...
  'bits',{'CTcap2TapSw',0,'CTcap1TapSw',1,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','thud_cmp','b','shatter_hang','c','n/c','outD','thud_declare','outQ','n/c'}, ...
  'loc',[9 3 0], ...
  'lut',{'lutIn','A & ~B','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','shatter_cmp','b','thud_hang','c','shatter_hang','outD','shatter_declare','outQ','n/c'}, ...
  'loc',[9 6 0], ...
  'lut',{'lutIn','A & B & ~C','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','inPos','tap','n/c','mega','diff_amp_amp_pos'}, ...
  'loc',[0 2], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_amp_pos','tap','n/c','mega','diff_amp_vmid'}, ...
  'loc',[0 3], ...
});
nethw{end+1}=ramp_ic.dev.opamp({ ...
  'net',{'pos','mid','neg','diff_amp_vmid','out','diff_amp_vmid'}, ...
  'nvm',{'bias','Id',5e-08,'vcg3'}, ...
  'loc',[0 3], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','inNeg','tap','n/c','mega','diff_amp_amp_neg'}, ...
  'loc',[0 4], ...
});
nethw{end+1}=ramp_ic.dev.resi({ ...
  'net',{'kilo','diff_amp_amp_neg','tap','n/c','mega','diff_amp'}, ...
  'loc',[0 5], ...
});
nethw{end+1}=ramp_ic.pin.A3({ ...
  'net',{'out','diff_amp_amp_pos','fb','diff_amp_amp_neg','in','diff_amp'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','inPos','out','inPos_pktop'}, ...
  'loc',[1 0 2], ...
  'nvm',{'atk','rate',41085.9,'vcg3','dec','rate',541.146,'vcg3','buff','Id',1e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','inPos_pktop','neg','inPos','out','CmpTop_cmp2int'}, ...
  'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.49721,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
  'loc',[4 0], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','vddLoc','well','vddLoc','gate','CmpTop_cmp2int','drain','CmpTop'}, ...
  'loc',[3 0], ...
  'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.peak({ ...
  'net',{'in','inPos','out','inPos_pkbot'}, ...
  'loc',[1 1 2], ...
  'nvm',{'atk','rate',621.796,'vcg3','dec','rate',34354.1,'vcg3','buff','Id',1e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.fgota({ ...
  'net',{'pos','inPos','neg','inPos_pkbot','out','CmpBot_cmp2int'}, ...
  'nvm',{'gm','gm',3e-06,'vcg3','posCharge','Vcg',1.50757,'vcg3','negCharge','Vcg',1.5,'vcg3'}, ...
  'loc',[4 1], ...
});
nethw{end+1}=ramp_ic.dev.pfet({ ...
  'net',{'source','vddLoc','well','vddLoc','gate','CmpBot_cmp2int','drain','CmpBot'}, ...
  'loc',[3 1], ...
  'nvm',{'sourceCur','Id',0,'vcg3','drainCur','Id',5e-07,'vcg3'}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','CmpTop','b','n/c','c','CmpTop_rst','outD','n/c','outQ','CmpTop_trig'}, ...
  'loc',[8 0 0], ...
  'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 0], ...
  'nvm',{'gm1','gm',0,'vcg3','gm2','gm',1e-06,'vcg3','pullCur','Id',9e-09,'vcg3','pushCur','Id',9e-09,'vcg3'}, ...
  'net',{'out','CmpTop_rst','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','CmpTop_trig','pGate','CmpTop_trig'}, ...
  'bits',{'CTcap2TapSw',0,'CTcap1TapSw',0,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','CmpBot','b','n/c','c','CmpBot_rst','outD','n/c','outQ','CmpBot_trig'}, ...
  'loc',[8 1 0], ...
  'lut',{'lutIn','1','lutClk','~A','lutRst','~C','lutD','1','lutNeighbor','1'}, ...
});
nethw{end+1}=ramp_ic.dev.ms({ ...
  'loc',[7 1], ...
  'nvm',{'gm1','gm',0,'vcg3','gm2','gm',1e-06,'vcg3','pullCur','Id',9e-09,'vcg3','pushCur','Id',9e-09,'vcg3'}, ...
  'net',{'out','CmpBot_rst','C1in','n/c','clkC1','n/c','clkN','n/c','clkP','n/c','ctrl','n/c','intNode','n/c','pos','n/c','neg','n/c','nGate','CmpBot_trig','pGate','CmpBot_trig'}, ...
  'bits',{'CTcap2TapSw',0,'CTcap1TapSw',0,'CTcapRatio',0,'CTcap2OutSw',0,'CTcap1InSw',0,'DTcap2TapSw',0,'DTcap1TapSw',0,'DTcapRatio',1,'DTcap2OutSw',0,'DTcap1InSw',0,'ota2follow',0,'ota2vgnd',1,'intNodeSw',0}, ...
});
nethw{end+1}=ramp_ic.dev.clb({ ...
  'net',{'a','CmpTop_trig','b','CmpBot_trig','c','n/c','outD','preroll_trig','outQ','n/c'}, ...
  'loc',[8 1 1], ...
  'lut',{'lutIn','A|B','lutClk','1','lutRst','1','lutD','Local','lutNeighbor','1'}, ...
});
